language: cpp

addons: 
  apt:
    packages:
      - ninja-build
  homebrew:
    packages:
      - ninja
      
matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: windows
      install: choco install ninja
    - os: osx

script:
  - cmake --version
  - ninja --version
  - cmake -GNinja
  - cmake --build .
