name: CMake

on: [push]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        buildtype: [Debug]
        platform: [android-on-linux]
        include:
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - os: ubuntu-latest
            platform: android-on-linux
            name: Android NDK
            ndkversion: android-ndk-r21d
          - os: ubuntu-latest
            platform: raspberry-on-linux
            name: Raspbian
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      if: ${{ startsWith(matrix.platform, 'android') }}
      with:
        java-version: 8

    - name: Setup NDK
      if: ${{ startsWith(matrix.platform, 'android') }}
      run: |
          wget -q https://dl.google.com/android/repository/${{ matrix.ndkversion }}-linux-x86_64.zip
          unzip -qq ${{ matrix.ndkversion }}-linux-x86_64.zip

    - name: Setup Raspi toolchain
      if: ${{ startsWith(matrix.platform, 'raspberry') }}
      run: |
          git clone https://github.com/raspberrypi/tools raspi-tools
          ls -la raspi-tools
          ls -la ${{github.workspace}}/raspi-tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake ( native )
      if: ${{ !startsWith(matrix.platform, 'android') && !startsWith(matrix.platform, 'raspberry') }}
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Configure CMake ( cross, Android )
      if: ${{ startsWith(matrix.platform, 'android') }}
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_NDK=${{github.workspace}}/${{ matrix.ndkversion }}

    - name: Configure CMake ( cross, Raspberry )
      if: ${{ startsWith(matrix.platform, 'raspberry') }}
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_CXX_COMPILER=${{github.workspace}}/raspi-tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-g++

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
