name: CMake

on: [push]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, android-on-linux] # macos, windows, android-on-linux]
        buildtype: [Debug]
        include:
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - os: ubuntu-latest
            platform: android-on-linux
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      if: ${{ startsWith(matrix.platform, 'android') }}
      with:
        java-version: 8

    - name: Setup NDK
      if: ${{ startsWith(matrix.platform, 'android') }}
      run: |
          echo "DL here"
          uname -a
          wget -q https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
          unzip -qq android-ndk-r21d-linux-x86_64.zip
          ls -la
          
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake ( native )
      if: ${{ !startsWith(matrix.platform, 'android') }}
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Configure CMake ( croww )
      if: ${{ startsWith(matrix.platform, 'android') }}
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE CMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21  -DCMAKE_ANDROID_NDK=android-ndk-r21d-linux-x86_64

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
